GET http://localhost:8080/GbJavaEESimple/api/v1/product/all
###
PUT http://localhost:8080/GbJavaEESimple/api/v1/product/new
Content-Type: application/json

{
  "title": "apple",
  "cost": 150,
  "category": {
    "id": 2,
    "title": "Category №1"
  }
}
###
GET http://localhost:8080/GbJavaEESimple/api/v1/product/6/id
###
GET http://localhost:8080/GbJavaEESimple/api/v1/category/all
###
DELETE http://localhost:8080/GbJavaEESimple/api/v1/category/2/id
Content-Type: application/json

{
  "id": 10,
  "title": "Category №9"
}